# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: blaine <blaine@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/15 16:41:40 by blaine            #+#    #+#              #
#    Updated: 2019/10/15 17:03:04 by blaine           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
CFILE = ft_display_file.c
OBJ = 

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) $(CFILE)

clean:
	-rm -f $(OBJ)

fclean: clean
	-rm -f $(NAME)

re: fclean all